apiVersion: v2
name: tailscale-subnet-router
description: Deploy a Tailscale subnet router on Kubernetes
type: application
version: 1.1.1
appVersion: "v1.30.0"
home: https://github.com/gtaylor/helm-charts/charts/tailscale-subnet-router
sources:
  - https://github.com/gtaylor/helm-charts/charts/tailscale-subnet-router
maintainers:
  - email: greg@gctaylor.com
    name: Greg Taylor
    url: https://gc-taylor.com
